"""swarm_pipeline.py -- Full cluster pipeline using all 9 clusters and 100+ models.

Usage:
    python -m autobots.swarm_pipeline "Build a tic-tac-toe game" D:\projects\output
"""

import json
import os
import sys
import time
import threading
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum

from openai import OpenAI

# -- Logging ----------------------------------------------------------------

LOG_DIR = Path(__file__).parent.parent / "logs"
LOG_DIR.mkdir(exist_ok=True)
timestamp = time.strftime("%Y%m%d_%H%M%S")
log_file = LOG_DIR / f"swarm_{timestamp}.log"

import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(log_file, encoding="utf-8"),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger("swarm")


# -- Skill System -----------------------------------------------------------

SKILLS_DIR = Path(__file__).parent.parent / "skills"

def load_skills_for_cluster(cluster_name: str, file_extensions: list[str] = None) -> str:
    """Load relevant skills for a cluster based on file types and cluster role."""
    skill_prompts = []
    
    # Map clusters to skill categories
    cluster_skill_map = {
        "Jazz": ["react-components", "tailwind-utils", "css-patterns"],
        "UltraMagnus": ["api-patterns", "state-management", "typescript-patterns"],
        "RedAlert": ["testing-patterns", "security-patterns"],
        "Ratchet": ["debug-patterns", "refactor-patterns"],
        "Perceptor": ["vite-setup", "build-config", "package-management"],
        "Optimus": ["planner-patterns", "architecture-patterns"],
    }
    
    # Get skills for this cluster
    skill_names = cluster_skill_map.get(cluster_name, [])
    
    # Add skills based on file extensions
    if file_extensions:
        for ext in file_extensions:
            if ext in [".tsx", ".jsx"]:
                if "react-components" not in skill_names:
                    skill_names.append("react-components")
            elif ext in [".css", ".scss"]:
                if "tailwind-utils" not in skill_names:
                    skill_names.append("tailwind-utils")
            elif ext in [".ts", ".js"]:
                if "typescript-patterns" not in skill_names:
                    skill_names.append("typescript-patterns")
    
    # Load skill files
    for skill_name in skill_names:
        skill_file = SKILLS_DIR / f"{skill_name}.md"
        if skill_file.exists():
            content = skill_file.read_text(encoding="utf-8")
            skill_prompts.append(f"=== SKILL: {skill_name} ===\n{content}\n=== END SKILL ===")
    
    # Also load any project-specific skills from output directory
    return "\n\n".join(skill_prompts)


def load_project_skills(project_path: Path) -> str:
    """Load skills generated by previous workers in this project."""
    skill_prompts = []
    skills_dir = project_path / ".autobots-skills"
    if skills_dir.exists():
        for skill_file in skills_dir.glob("*.md"):
            content = skill_file.read_text(encoding="utf-8")
            skill_prompts.append(f"=== PROJECT SKILL: {skill_file.stem} ===\n{content}\n=== END SKILL ===")
    return "\n\n".join(skill_prompts)


def create_skill_from_task(task, files: list[dict], project_path: Path):
    """Create a skill file from a successful task for future use."""
    if not files or task.status != "done":
        return
    
    skills_dir = project_path / ".autobots-skills"
    skills_dir.mkdir(exist_ok=True)
    
    # Build file list for skill
    file_list = "\n".join([f'- {f.get("path", "unknown")}' for f in files])
    
    # Create skill content with better structure
    skill_content = f"""---
name: {task.cluster.lower()}-{task.task_id.lower()}
description: Auto-generated skill from {task.cluster} cluster for {task.description[:100]}
nim_model: {task.model_used}
nim_endpoint: https://integrate.api.nvidia.com/v1
---

# {task.cluster} Skill: {task.description}

## Files Generated
{file_list}

## Cluster
{task.cluster}

## Model Used
{task.model_used}

## Pattern
This skill was generated from a successful task execution. Use it as a reference
for similar tasks in the future.

## Usage
When similar tasks appear, reference this skill to maintain consistency.
"""
    
    skill_file = skills_dir / f"{task.cluster.lower()}-{task.task_id.lower()}.md"
    skill_file.write_text(skill_content, encoding="utf-8")
    logger.info(f"[SKILL] Created skill: {skill_file.name}")


# -- All 9 Clusters --------------------------------------------------------

CLUSTERS = {
    "Optimus": {
        "role": "command-and-routing",
        "desc": "Planning, roadmaps, architecture, orchestration",
        "models": [
            "qwen/qwen3-next-80b-a3b-instruct",
            "qwen/qwen3.5-122b-a10b",
            "stepfun-ai/step-3.5-flash",
            "meta/llama-3.3-70b-instruct",
        ],
        "system_prompt": """You are a project planner and architect. Decompose goals into detailed tasks.

For each task, specify:
- task_id: unique identifier (T1, T2, etc.)
- description: what to build
- files: file paths to generate
- cluster: which cluster should handle this (Optimus/UltraMagnus/RedAlert/Jazz/Ratchet/Perceptor/Bumblebee/Ironhide/Wheeljack)
- depends_on: list of task IDs this depends on
- priority: high/medium/low

Also provide:
- type_contracts: TypeScript interfaces all workers must use
- architecture: brief architecture overview

Return JSON with key "items" (not "tasks") containing the task list.

Rules:
- Each task gets 1-3 files max
- Independent tasks should have empty depends_on
- Assign to correct cluster based on task nature
- UI tasks -> Jazz, Logic -> UltraMagnus, Security -> RedAlert, Config -> Perceptor, Tests -> Ratchet""",
    },
    "UltraMagnus": {
        "role": "backend-and-architecture",
        "desc": "APIs, databases, services, Python, integrations",
        "models": [
            "qwen/qwen3-next-80b-a3b-instruct",
            "qwen/qwen3.5-122b-a10b",
            "meta/llama-3.3-70b-instruct",
            "stepfun-ai/step-3.5-flash",
        ],
        "system_prompt": """You are a backend and architecture specialist. Build these files: {files}

Context: {context}

BACKEND RULES:
- Clean, well-structured code
- TypeScript types where applicable
- Proper error handling
- Follow TYPE CONTRACTS from context exactly
- Export default for main modules

IMPORTANT: Reply with valid JSON only.
Return: {{"files": [{{"path": "...", "content": "..."}}]}}""",
    },
    "RedAlert": {
        "role": "security-and-safety",
        "desc": "Auth, guardrails, PII, validation, policies",
        "models": [
            "qwen/qwen3-next-80b-a3b-instruct",
            "qwen/qwen3.5-122b-a10b",
            "stepfun-ai/step-3.5-flash",
        ],
        "system_prompt": """You are a security and code review specialist. Build these files: {files}

Context: {context}

REVIEW RULES:
- Check for type errors, missing imports, broken references
- Validate all function signatures match contracts
- Ensure proper error handling
- Return ALL files with fixes applied

IMPORTANT: Reply with valid JSON only.
Return: {{"files": [{{"path": "...", "content": "..."}}]}}""",
    },
    "Jazz": {
        "role": "frontend-and-creative",
        "desc": "UI/UX, CSS, Tailwind, components, images, visuals",
        "models": [
            "qwen/qwen3-next-80b-a3b-instruct",
            "qwen/qwen3.5-122b-a10b",
            "stepfun-ai/step-3.5-flash",
            "google/gemma-4-31b-it",
        ],
        "system_prompt": """You are a UI/UX specialist. Build these files: {files}

Context: {context}

DESIGN RULES:
- Modern CSS: flexbox/grid, gap, rounded corners, smooth transitions
- Colors: cohesive palette (blues #3b82f6/#60a5fa/#1e40af or slates)
- Hover effects on buttons (transform, shadow changes)
- Box-shadow for depth: 0 4px 6px -1px rgba(0,0,0,0.1)
- Typography: font-weight 600-700 headings, 14-16px body
- Transitions: all 0.2s ease on interactive elements
- Dark backgrounds: #0f172a, #1e293b, #334155
- Light backgrounds: #f8fafc, #f1f5f9, #e2e8f0
- Gradient accents: linear-gradient(135deg, color1, color2)
- Spacing: 16-24px padding, 8-12px gap
- Responsive: use %, rem, or vh/vw units

IMPORTANT: Reply with valid JSON only.
Return: {{"files": [{{"path": "...", "content": "..."}}]}}""",
    },
    "Ratchet": {
        "role": "debug-and-repair",
        "desc": "Debugging, fixing, refactoring, patching, tests",
        "models": [
            "qwen/qwen3-next-80b-a3b-instruct",
            "qwen/qwen3.5-122b-a10b",
            "stepfun-ai/step-3.5-flash",
        ],
        "system_prompt": """You are a logic and game logic specialist. Build these files: {files}

Context: {context}

LOGIC RULES:
- Clean, well-structured code
- TypeScript types where applicable
- Follow TYPE CONTRACTS from context exactly
- Proper error handling
- Export default for main modules

IMPORTANT: Reply with valid JSON only.
Return: {{"files": [{{"path": "...", "content": "..."}}]}}""",
    },
    "Perceptor": {
        "role": "retrieval-and-parsing",
        "desc": "Config files, build setup, package management",
        "models": [
            "qwen/qwen3-next-80b-a3b-instruct",
            "stepfun-ai/step-3.5-flash",
        ],
        "system_prompt": """You are a build/config specialist. Build these files: {files}

Context: {context}

BUILD RULES:
- Generate proper package.json with correct dependencies
- Generate correct TypeScript config
- Generate proper Vite/build config
- Ensure all imports resolve correctly

IMPORTANT: Reply with valid JSON only.
Return: {{"files": [{{"path": "...", "content": "..."}}]}}""",
    },
    "Bumblebee": {
        "role": "communication-and-media",
        "desc": "Speech, voice, translation, media (not used for web apps)",
        "models": ["qwen/qwen3-next-80b-a3b-instruct"],
        "system_prompt": None,
    },
    "Ironhide": {
        "role": "physical-and-simulation",
        "desc": "Physics, optimization, routing (not used for web apps)",
        "models": ["qwen/qwen3-next-80b-a3b-instruct"],
        "system_prompt": None,
    },
    "Wheeljack": {
        "role": "scientific-specialist",
        "desc": "Science, molecules, proteins (not used for web apps)",
        "models": ["qwen/qwen3-next-80b-a3b-instruct"],
        "system_prompt": None,
    },
}

# Map task types to clusters
TASK_CLUSTER_MAP = {
    "ui-component": "Jazz",
    "ui-style": "Jazz",
    "ui-layout": "Jazz",
    "frontend": "Jazz",
    "component": "Jazz",
    "css": "Jazz",
    "tailwind": "Jazz",
    "api-endpoint": "UltraMagnus",
    "business-logic": "UltraMagnus",
    "data-model": "UltraMagnus",
    "database": "UltraMagnus",
    "backend": "UltraMagnus",
    "service": "UltraMagnus",
    "security": "RedAlert",
    "auth": "RedAlert",
    "validation": "RedAlert",
    "review": "RedAlert",
    "unit-test": "Ratchet",
    "integration-test": "Ratchet",
    "debug": "Ratchet",
    "fix": "Ratchet",
    "refactor": "Ratchet",
    "logic": "Ratchet",
    "game-logic": "Ratchet",
    "boilerplate": "Perceptor",
    "config": "Perceptor",
    "build": "Perceptor",
    "setup": "Perceptor",
}


# -- Rate Limiter -----------------------------------------------------------

class RateLimiter:
    def __init__(self, max_per_minute=35, min_interval=2.0):
        self.max_per_minute = max_per_minute
        self.min_interval = min_interval
        self.calls = []
        self.lock = threading.Lock()

    def wait_if_needed(self):
        with self.lock:
            now = time.time()
            self.calls = [t for t in self.calls if now - t < 60]
            if self.calls:
                elapsed = now - self.calls[-1]
                if elapsed < self.min_interval:
                    time.sleep(self.min_interval - elapsed)
                    now = time.time()
                    self.calls = [t for t in self.calls if now - t < 60]
            if len(self.calls) >= self.max_per_minute:
                wait_time = 60 - (now - self.calls[0]) + 0.5
                logger.info(f"[rate-limit] Waiting {wait_time:.1f}s (limit reached)")
                time.sleep(wait_time)
                now = time.time()
                self.calls = [t for t in self.calls if now - t < 60]
            self.calls.append(time.time())

    def backoff(self):
        logger.info("[rate-limit] Backoff: waiting 30s")
        time.sleep(30)


# -- JSON Parser ------------------------------------------------------------

def parse_json_response(content, label=""):
    if not content:
        logger.debug(f"[json] Empty content for {label}")
        return None

    import re
    content = content.strip()

    # Remove markdown code fences
    if content.startswith("```json"):
        content = content[7:]
    if content.startswith("```"):
        content = content[3:]
    if content.endswith("```"):
        content = content[:-3]
    content = content.strip()

    # Try to find JSON object
    match = re.search(r"\{.*\}", content, re.DOTALL)
    if not match:
        # Try to find code blocks with TypeScript/JavaScript
        code_block = re.search(r"(?:typescript|javascript|ts|js)\s*\n(.*?)$", content, re.DOTALL)
        if code_block:
            code = code_block.group(1).strip()
            path_match = re.search(r"//\s*(src/\S+)", code)
            path = path_match.group(1) if path_match else "src/unknown.ts"
            return {"files": [{"path": path, "content": code}]}
        logger.debug(f"[json] No JSON found for {label}")
        return None

    raw = match.group()

    # Try direct parse
    try:
        return json.loads(raw, strict=False)
    except json.JSONDecodeError:
        pass

    # Try various fixes
    fixes = [
        lambda s: s.replace('\n', '\\n'),
        lambda s: s.replace('\r', ''),
        lambda s: s.replace('\t', '\\t'),
        lambda s: re.sub(r",\s*([}\]])", r"\1", s),
        lambda s: s.replace('\\\\n', '\\n'),
        lambda s: s.replace('\\"', '"'),
        lambda s: re.sub(r"\\/", "/", s),
        lambda s: re.sub(r"[\x00-\x1f]", " ", s),
    ]
    for fix in fixes:
        try:
            return json.loads(fix(raw))
        except json.JSONDecodeError:
            continue

    # Try to extract just the files array
    files_match = re.search(r'"files"\s*:\s*\[.*?\]', raw, re.DOTALL)
    if files_match:
        try:
            return json.loads("{" + files_match.group() + "}")
        except json.JSONDecodeError:
            pass

    # Try to extract items or tasks array
    items_match = re.search(r'"(?:items|tasks)"\s*:\s*\[.*?\]', raw, re.DOTALL)
    if items_match:
        try:
            return json.loads("{" + items_match.group() + "}")
        except json.JSONDecodeError:
            pass

    # Last resort: try to fix common JSON issues
    try:
        # Remove trailing commas
        fixed = re.sub(r",\s*([}\]])", r"\1", raw)
        # Fix unescaped newlines in strings
        fixed = re.sub(r'(?<=")[^"]*(?=")', lambda m: m.group().replace('\n', '\\n'), fixed)
        return json.loads(fixed)
    except json.JSONDecodeError:
        pass

    logger.debug(f"[json] All parse attempts failed for {label}")
    return None


# -- Task Dataclass ---------------------------------------------------------

@dataclass
class Task:
    task_id: str
    description: str
    files: list[str]
    cluster: str
    depends_on: list[str] = field(default_factory=list)
    priority: str = "medium"
    status: str = "pending"  # pending, running, done, failed
    model_used: str = ""
    elapsed: float = 0.0


def normalize_files(files):
    """Convert file specs to strings. Handles both 'path' strings and {'path':..., 'content':...} dicts."""
    result = []
    for f in files:
        if isinstance(f, dict):
            result.append(f.get("path", ""))
        else:
            result.append(str(f))
    return [f for f in result if f]


# -- Planner ----------------------------------------------------------------

def plan_tasks(goal, rate_limiter):
    """Use Optimus cluster to decompose goal into tasks with cluster assignments."""
    logger.info(f"\n{'='*60}")
    logger.info(f"[OPTIMUS] Planning: {goal}")
    logger.info(f"{'='*60}")

    client = OpenAI(
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=os.environ.get("NVIDIA_API_KEY", ""),
    )

    cluster_info = "\n".join([
        f"  - {k}: {v['desc']}" for k, v in CLUSTERS.items()
        if v["system_prompt"] is not None
    ])

    system = f"""You are the planning agent for autobot-swarm. Given a task, produce a structured execution plan.

Available clusters:
{cluster_info}

Your plan must identify:
1. Which subtasks can run in parallel vs. which must be sequential
2. Which cluster is best suited for each subtask
3. What the success criteria are for each step
4. What the milestone gates are (points where progress is reviewed before continuing)

CRITICAL: This project uses Tailwind CSS v4 with Vite. The correct setup is:
- postcss.config.js: export default {{ plugins: {{ "@tailwindcss/postcss": {{}} }} }};
- package.json must include: "tailwindcss": "^4.0.0", "@tailwindcss/vite": "^4.0.0", "@tailwindcss/postcss": "^4.0.0"
- vite.config.js must use: import tailwindcss from "@tailwindcss/vite"; export default defineConfig({{ plugins: [tailwindcss()] }});
- Do NOT use "tailwindcss" directly as a PostCSS plugin - use "@tailwindcss/postcss" instead

For each task, specify:
- task_id: unique ID (T1, T2, etc.)
- description: what to build
- files: file paths to generate (1-3 files max)
- cluster: which cluster handles this
- depends_on: task IDs this depends on (empty if independent)
- priority: high/medium/low
- success_criteria: how to know this task succeeded

Also provide:
- type_contracts: TypeScript interfaces all workers must use
- architecture: brief overview
- estimated_complexity: low | medium | high
- total_nim_calls_estimated: estimated API calls
- rate_limit_risk: low | medium | high

Return JSON: {{
  "task_summary": "One sentence description of the task",
  "estimated_complexity": "medium",
  "tasks": [{{"task_id": "T1", "description": "...", "files": ["..."], "cluster": "...", "depends_on": [], "priority": "high", "success_criteria": "..."}}],
  "type_contracts": "...",
  "architecture": "...",
  "total_nim_calls_estimated": 12,
  "rate_limit_risk": "low"
}}

Rules:
- Each task gets 1-3 files max
- Assign UI/visual tasks to Jazz
- Assign logic/state tasks to Ratchet or UltraMagnus
- Assign config/build to Perceptor
- Assign test/review to RedAlert
- Independent tasks: empty depends_on
- At least one milestone gate for high complexity tasks
- Sequential dependencies must be explicit (task B lists task A's output as input)"""

    user = f"""Goal: {goal}

Decompose into tasks with cluster assignments.

IMPORTANT: Define ALL import paths in the shared context so workers can reference each other's files.
For each task, specify the exact exports other tasks should import.
Example: "T1 exports: CardProps interface, Card component, default export"

Workers must use these exact import paths to avoid cross-worker import mismatches."""

    for attempt in range(3):
        rate_limiter.wait_if_needed()
        try:
            start = time.time()
            r = client.chat.completions.create(
                model=CLUSTERS["Optimus"]["models"][0],
                messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
                max_tokens=4096,
                temperature=0.3,
                timeout=120,
            )
            elapsed = time.time() - start
            content = r.choices[0].message.content or ""
            logger.info(f"[OPTIMUS] Response in {elapsed:.1f}s (attempt {attempt+1})")

            with open(LOG_DIR / f"planner_{timestamp}.json", "w", encoding="utf-8") as f:
                json.dump({"model": CLUSTERS["Optimus"]["models"][0], "elapsed": elapsed, "content": content}, f, indent=2, ensure_ascii=False)

            data = parse_json_response(content, "planner")
            if data and ("tasks" in data or "items" in data):
                task_list = data.get("tasks") or data.get("items", [])
                tasks = []
                for t in task_list:
                    task = Task(
                        task_id=t.get("task_id", f"T{len(tasks)+1}"),
                        description=t.get("description", ""),
                        files=normalize_files(t.get("files", [])),
                        cluster=t.get("cluster", "Ratchet"),
                        depends_on=t.get("depends_on", []),
                        priority=t.get("priority", "medium"),
                    )
                    tasks.append(task)

                type_contracts = data.get("type_contracts", "")
                architecture = data.get("architecture", "")
                complexity = data.get("estimated_complexity", "medium")
                nim_calls = data.get("total_nim_calls_estimated", len(tasks) * 2)
                rate_risk = data.get("rate_limit_risk", "low")

                logger.info(f"[OPTIMUS] Planned {len(tasks)} tasks (complexity: {complexity}, rate risk: {rate_risk}):")
                for t in tasks:
                    deps = ",".join(t.depends_on) if t.depends_on else "none"
                    logger.info(f"  {t.task_id} [{t.cluster}] {t.description[:50]}... (depends: {deps})")

                # Store metadata for rate limiting
                metadata = {
                    "complexity": complexity,
                    "nim_calls_estimated": nim_calls,
                    "rate_limit_risk": rate_risk,
                }

                return tasks, type_contracts, architecture
            else:
                logger.warning(f"[OPTIMUS] Failed to parse response (attempt {attempt+1}/3)")
                continue

        except Exception as e:
            logger.error(f"[OPTIMUS] Error (attempt {attempt+1}/3): {e}")
            continue

    logger.error("[OPTIMUS] All 3 planning attempts failed")
    return [], "", ""


# -- Worker -----------------------------------------------------------------

def execute_task(task, shared_context, rate_limiter, project_path=None):
    """Execute a single task using its assigned cluster's model."""
    cluster_config = CLUSTERS.get(task.cluster)
    if not cluster_config or not cluster_config["system_prompt"]:
        logger.warning(f"[{task.task_id}] No prompt for cluster {task.cluster}, skipping")
        task.status = "failed"
        return []

    model_id = cluster_config["models"][0]
    model_name = model_id.split("/")[-1]

    logger.info(f"\n{'-'*60}")
    logger.info(f"[{task.task_id}] [cluster: {task.cluster} | model: {model_name}] working on: {task.description[:80]}")
    logger.info(f"  Files: {', '.join(task.files)}")

    task.status = "running"
    task.model_used = model_name

    client = OpenAI(
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=os.environ.get("NVIDIA_API_KEY", ""),
    )

    # Load skills for this cluster
    file_extensions = [Path(f).suffix for f in task.files if f]
    cluster_skills = load_skills_for_cluster(task.cluster, file_extensions)
    project_skills = load_project_skills(project_path) if project_path else ""
    
    # Build enhanced system prompt with skills
    system = cluster_config["system_prompt"].format(
        files=", ".join(task.files),
        context=shared_context,
    )
    
    # Add skills to prompt
    if cluster_skills:
        system += f"\n\n{cluster_skills}"
    if project_skills:
        system += f"\n\n{project_skills}"

    try:
        rate_limiter.wait_if_needed()
        start = time.time()

        max_retries = 3
        for attempt in range(max_retries):
            try:
                r = client.chat.completions.create(
                    model=model_id,
                    messages=[{"role": "system", "content": system}, {"role": "user", "content": task.description}],
                    max_tokens=4096,
                    temperature=0.3,
                    timeout=120,
                )
                break
            except Exception as e:
                if ("429" in str(e) or "timed out" in str(e).lower() or "DEGRADED" in str(e)) and attempt < max_retries - 1:
                    logger.warning(f"[{task.task_id}] Retry {attempt + 1}: {type(e).__name__}")
                    rate_limiter.backoff()
                    continue
                raise

        elapsed = time.time() - start
        task.elapsed = elapsed
        content = r.choices[0].message.content or ""

        with open(LOG_DIR / f"task_{task.task_id}_{timestamp}.json", "w", encoding="utf-8") as f:
            json.dump({
                "task_id": task.task_id,
                "cluster": task.cluster,
                "model": model_id,
                "elapsed": elapsed,
                "content": content,
            }, f, indent=2, ensure_ascii=False)

        data = parse_json_response(content, task.task_id)
        if data and "files" in data:
            files = data["files"]
            requested_set = set(task.files)
            filtered = [f for f in files if f.get("path", "") in requested_set]

            if not filtered:
                filtered = files

            task.status = "done"
            logger.info(f"[{task.task_id}] [OK] Done in {elapsed:.1f}s -> {len(filtered)} files")
            return filtered
        else:
            logger.error(f"[{task.task_id}] [FAIL] Failed to parse response")
            task.status = "failed"
            return []

    except Exception as e:
        logger.error(f"[{task.task_id}] [FAIL] Error: {e}")
        task.status = "failed"
        return []


# -- Code Review Gate -------------------------------------------------------

def review_code(task, files: list[dict], shared_context: str, rate_limiter) -> list[dict]:
    """Review code quality using minimax-m2.7 before writing to disk."""
    if not files:
        return files
    
    # Build combined code for review
    code_for_review = "\n\n".join([
        f"=== FILE: {f.get('path', 'unknown')} ===\n{f.get('content', '')}"
        for f in files
    ])
    
    system = """You are a senior software engineer reviewing code produced by an AI agent.

Review focus: correctness, security, performance, and autobot-swarm compatibility

Return a JSON object with this exact shape:
{
  "verdict": "approve" | "revise" | "reject",
  "score": 0-100,
  "critical": ["list of blocking issues"],
  "warnings": ["list of non-blocking issues"],
  "suggestions": ["list of improvements"],
  "fixed_files": [{"path": "...", "content": "..."}] // only if verdict is revise
}

Rules:
- approve: score >= 80 and zero critical issues
- revise: score 50-79 or non-blocking issues, return fixed_files
- reject: score < 50 or any security-critical issue"""
    
    user = f"""Task: {task.description}
Cluster: {task.cluster}

Code to review:
{code_for_review}

Review this code and return JSON with verdict, score, and fixed_files if needed."""
    
    try:
        rate_limiter.wait_if_needed()
        client = OpenAI(
            base_url="https://integrate.api.nvidia.com/v1",
            api_key=os.environ.get("NVIDIA_API_KEY", ""),
        )
        
        r = client.chat.completions.create(
            model="minimax/minimax-m2.7",
            messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
            max_tokens=4096,
            temperature=0.1,
            timeout=120,
        )
        
        content = r.choices[0].message.content or ""
        data = parse_json_response(content, f"review-{task.task_id}")
        
        if data:
            verdict = data.get("verdict", "approve")
            score = data.get("score", 0)
            critical = data.get("critical", [])
            
            logger.info(f"[REVIEW] {task.task_id}: {verdict} (score: {score}, critical: {len(critical)})")
            
            if verdict == "reject":
                logger.warning(f"[REVIEW] {task.task_id}: REJECTED - {critical}")
                return []
            elif verdict == "revise":
                fixed = data.get("fixed_files", [])
                if fixed:
                    logger.info(f"[REVIEW] {task.task_id}: Revised with {len(fixed)} files")
                    return fixed
        
        # Default: return original files
        return files
        
    except Exception as e:
        # If model not available (404), skip review and use original files
        if "404" in str(e):
            logger.debug(f"[REVIEW] {task.task_id}: Model not available, skipping review")
        else:
            logger.warning(f"[REVIEW] {task.task_id}: Review failed ({e}), using original files")
        return files


# -- Output Guardrail -------------------------------------------------------

def validate_output(task, files: list[dict], rate_limiter) -> list[dict]:
    """Validate output using nemotron-content-safety before writing to disk."""
    if not files:
        return files
    
    # Build combined content for validation
    content_for_validation = "\n\n".join([
        f"=== FILE: {f.get('path', 'unknown')} ===\n{f.get('content', '')}"
        for f in files
    ])
    
    system = """You are a content safety validator. Analyze the output for safety issues.

Return JSON: {safe: bool, issues: [], severity: 'none'|'low'|'high', spec_compliant: bool, spec_issues: []}

Check for:
- Malformed content
- Unsafe or inappropriate content
- Off-spec responses
- Quality standard violations"""
    
    user = f"""Task: {task.description}
Cluster: {task.cluster}

Content to validate:
{content_for_validation[:4000]}"""
    
    try:
        rate_limiter.wait_if_needed()
        client = OpenAI(
            base_url="https://integrate.api.nvidia.com/v1",
            api_key=os.environ.get("NVIDIA_API_KEY", ""),
        )
        
        r = client.chat.completions.create(
            model="nvidia/nemotron-content-safety",
            messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
            max_tokens=500,
            temperature=0.0,
            timeout=60,
        )
        
        content = r.choices[0].message.content or ""
        data = parse_json_response(content, f"guardrail-{task.task_id}")
        
        if data:
            safe = data.get("safe", True)
            severity = data.get("severity", "none")
            issues = data.get("issues", [])
            
            if not safe and severity == "high":
                logger.warning(f"[GUARDRAIL] {task.task_id}: BLOCKED - {issues}")
                return []
            elif issues:
                logger.info(f"[GUARDRAIL] {task.task_id}: WARN - {len(issues)} issues")
        
        # Default: return original files
        return files
        
    except Exception as e:
        # If model not available (404), skip guardrail and use original files
        if "404" in str(e):
            logger.debug(f"[GUARDRAIL] {task.task_id}: Model not available, skipping guardrail")
        else:
            logger.warning(f"[GUARDRAIL] {task.task_id}: Validation failed ({e}), using original files")
        return files


# -- Dependency Resolver ----------------------------------------------------

def get_ready_tasks(tasks):
    """Return tasks whose dependencies are all done."""
    ready = []
    for t in tasks:
        if t.status != "pending":
            continue
        deps_met = all(
            any(other.task_id == dep and other.status == "done" for other in tasks)
            for dep in t.depends_on
        )
        if deps_met:
            ready.append(t)
    return ready


# -- File Verification ------------------------------------------------------

# Critical files that must exist for a React+Vite project
CRITICAL_FILES = {
    "index.html": '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>App</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>',
    "src/main.tsx": 'import React from "react";\nimport ReactDOM from "react-dom/client";\nimport App from "./App";\nimport "./index.css";\nReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);',
    "src/index.css": '@import "tailwindcss";',
    "tsconfig.json": '{"compilerOptions":{"target":"ES2020","useDefineForClassFields":true,"lib":["ES2020","DOM","DOM.Iterable"],"module":"ESNext","skipLibCheck":true,"moduleResolution":"bundler","allowImportingTsExtensions":true,"resolveJsonModule":true,"isolatedModules":true,"noEmit":true,"jsx":"react-jsx","strict":true},"include":["src"]}',
    "postcss.config.js": 'export default { plugins: { "@tailwindcss/postcss": {} } };',
    "package.json": '{\n  "name": "app",\n  "private": true,\n  "version": "0.0.0",\n  "type": "module",\n  "scripts": {\n    "dev": "vite",\n    "build": "vite build",\n    "preview": "vite preview"\n  },\n  "dependencies": {\n    "react": "^19.1.0",\n    "react-dom": "^19.1.0"\n  },\n  "devDependencies": {\n    "@types/react": "^19.1.0",\n    "@types/react-dom": "^19.1.0",\n    "@vitejs/plugin-react": "^4.4.0",\n    "typescript": "~5.8.0",\n    "vite": "^6.4.0",\n    "tailwindcss": "^4.0.0",\n    "@tailwindcss/vite": "^4.0.0",\n    "@tailwindcss/postcss": "^4.0.0"\n  }\n}',
}


def verify_files(project_path, tasks):
    """Check which planned files actually exist on disk. Also check critical boilerplate."""
    missing = []
    empty = []

    # Check planned files
    for t in tasks:
        for f in t.files:
            full = project_path / f
            if not full.exists():
                missing.append({"task_id": t.task_id, "file": f, "cluster": t.cluster})
            elif full.stat().st_size == 0:
                empty.append({"task_id": t.task_id, "file": f, "cluster": t.cluster})

    # Check critical boilerplate files
    for filename in CRITICAL_FILES:
        full = project_path / filename
        if not full.exists():
            missing.append({"task_id": "CRITICAL", "file": filename, "cluster": "Perceptor"})
        elif full.stat().st_size == 0:
            empty.append({"task_id": "CRITICAL", "file": filename, "cluster": "Perceptor"})

    return missing, empty


def write_critical_files(project_path):
    """Write critical boilerplate files if missing."""
    written = 0
    for filename, content in CRITICAL_FILES.items():
        full = project_path / filename
        if not full.exists():
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text(content, encoding="utf-8")
            logger.info(f"[CRITICAL] Created {filename}")
            written += 1
    return written


def verify_logic(project_path):
    """Basic logic checks: imports resolve, no obvious broken references."""
    issues = []
    src_dir = project_path / "src"
    if not src_dir.exists():
        issues.append("No src/ directory found")
        return issues

    ts_files = list(src_dir.rglob("*.ts")) + list(src_dir.rglob("*.tsx"))
    for f in ts_files:
        rel = f.relative_to(project_path).as_posix()
        content = f.read_text(encoding="utf-8", errors="ignore")
        lines = content.split("\n")
        for i, line in enumerate(lines):
            if "from '" in line or 'from "' in line:
                import_match = line.split("from ")[-1].strip().strip("'\"").rstrip(";")
                if import_match.startswith("./") or import_match.startswith("../"):
                    file_dir = f.parent
                    resolved = (file_dir / import_match).as_posix()
                    candidates = [
                        project_path / f"{resolved}.tsx",
                        project_path / f"{resolved}.ts",
                        project_path / f"{resolved}.jsx",
                        project_path / f"{resolved}.js",
                        project_path / resolved / "index.tsx",
                        project_path / resolved / "index.ts",
                    ]
                    if not any(c.exists() for c in candidates):
                        issues.append(f"{rel}:{i+1} imports '{import_match}' but file not found")
    return issues


# -- Shell Commands ----------------------------------------------------------

def run_shell(command, cwd, timeout=120):
    """Run a shell command, return (success, stdout+stderr)."""
    import subprocess
    try:
        result = subprocess.run(
            command,
            shell=True,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        output = result.stdout + "\n" + result.stderr
        return result.returncode == 0, output.strip()
    except subprocess.TimeoutExpired:
        return False, f"TIMEOUT after {timeout}s running: {command}"
    except Exception as e:
        return False, str(e)


def install_deps(project_path):
    """Run npm install. Returns (success, error_output)."""
    logger.info("\n[INSTALL] Running npm install...")
    ok, output = run_shell("npm install", cwd=project_path, timeout=180)
    if ok:
        logger.info("[INSTALL] npm install OK")
    else:
        logger.error(f"[INSTALL] npm install FAILED:\n{output}")
    return ok, output


def build_project(project_path):
    """Run vite build. Returns (success, error_output)."""
    logger.info("\n[BUILD] Running npx vite build...")
    ok, output = run_shell("npx vite build", cwd=project_path, timeout=120)
    if ok:
        logger.info("[BUILD] Build OK")
    else:
        logger.error(f"[BUILD] Build FAILED:\n{output}")
    return ok, output


def plan_build_fix(goal, build_errors, rate_limiter, project_path):
    """Ask planner to create fix tasks for build errors."""
    logger.info(f"\n[BUILD-FIX] Planning fixes for build errors")

    rate_limiter.wait_if_needed()

    client = OpenAI(
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=os.environ.get("NVIDIA_API_KEY", ""),
    )

    existing_files = "\n".join([
        f"- {f.relative_to(project_path).as_posix()}"
        for f in project_path.rglob("*")
        if f.is_file() and "node_modules" not in str(f) and "swarm_" not in f.name
    ])

    system = """You are a build-error fix planner. The project failed to compile/install. Create fix tasks.

CRITICAL: This project uses Tailwind CSS v4 with Vite. The correct setup is:
- postcss.config.js: export default { plugins: { "@tailwindcss/postcss": {} } };
- package.json must include: "tailwindcss": "^4.0.0", "@tailwindcss/vite": "^4.0.0", "@tailwindcss/postcss": "^4.0.0"
- vite.config.js must use: import tailwindcss from "@tailwindcss/vite"; export default defineConfig({ plugins: [tailwindcss()] });
- Do NOT use "tailwindcss" directly as a PostCSS plugin - use "@tailwindcss/postcss" instead

For each fix task, specify:
- task_id: unique ID (FIX1, FIX2, etc.)
- description: what to fix
- files: file paths to create or rewrite (full content required)
- cluster: which cluster handles this
- depends_on: empty for independent fixes
- priority: high

Return JSON with key "items" containing the task list.

Rules:
- Each fix task gets 1-3 files max
- Read the error message carefully -- fix the exact issue
- Common issues: missing imports, wrong Tailwind version, wrong package.json deps, broken JSX, missing types
- If package.json needs fixing, include the FULL corrected package.json
- If vite.config.js needs fixing, include FULL corrected file
- Assign UI fixes to Jazz, logic to UltraMagnus/Ratchet, config to Perceptor"""

    user = f"""Goal: {goal}

BUILD ERRORS:
{build_errors}

EXISTING FILES:
{existing_files}

Create fix tasks to resolve the build errors. Include FULL file contents for every file you fix."""

    try:
        response = client.chat.completions.create(
            model="qwen/qwen3-next-80b-a3b-instruct",
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=0.3,
            max_tokens=16384,
        )
        raw = response.choices[0].message.content or ""
        logger.info(f"[BUILD-FIX] Planner response in {response.usage.completion_tokens} tokens")

        # Parse JSON
        clean = raw.strip()
        if clean.startswith("```json"):
            clean = clean[7:]
        if clean.endswith("```"):
            clean = clean[:-3]
        clean = clean.strip()

        data = json.loads(clean)
        items = data.get("items", data.get("tasks", []))

        fix_tasks = []
        for item in items:
            fix_tasks.append(Task(
                task_id=item.get("task_id", f"FIX{len(fix_tasks)+1}"),
                description=item.get("description", ""),
                files=normalize_files(item.get("files", [])),
                cluster=item.get("cluster", "Ratchet"),
                depends_on=item.get("depends_on", []),
                priority=item.get("priority", "high"),
            ))

        logger.info(f"[BUILD-FIX] Created {len(fix_tasks)} fix tasks")
        return fix_tasks

    except Exception as e:
        logger.error(f"[BUILD-FIX] Planner error: {e}")
        return []


# -- Remediation Planner ----------------------------------------------------

def plan_remediation(goal, failed_tasks, missing_files, logic_issues, existing_tasks, rate_limiter, project_path):
    """Ask planner to create fix tasks for failures."""
    logger.info(f"\n[REMEDIATION] Planning fixes for {len(failed_tasks)} failures, {len(missing_files)} missing files, {len(logic_issues)} logic issues")

    rate_limiter.wait_if_needed()

    client = OpenAI(
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=os.environ.get("NVIDIA_API_KEY", ""),
    )

    failure_report = "\n".join([
        f"- {t.task_id} [{t.cluster}]: {t.description} -- FAILED ({t.model_used})"
        for t in failed_tasks
    ])
    missing_report = "\n".join([
        f"- {m['file']} (was task {m['task_id']})"
        for m in missing_files
    ])
    logic_report = "\n".join([f"- {issue}" for issue in logic_issues[:20]])
    existing_files = "\n".join([
        f"- {f}" for f in (project_path / "src").rglob("*")
        if f.is_file() and "node_modules" not in str(f)
    ]) if (project_path / "src").exists() else "None"

    system = """You are a remediation planner. Given failures and missing files, create fix tasks.

For each fix task, specify:
- task_id: unique ID (FIX1, FIX2, etc.)
- description: what to fix
- files: file paths to create or fix
- cluster: which cluster handles this
- depends_on: empty for independent fixes
- priority: high

Return JSON with key "items" containing the task list.

Rules:
- Each fix task gets 1-3 files max
- Focus on creating missing files first
- Then fix logic/import issues
- Assign UI fixes to Jazz, logic to UltraMagnus/Ratchet, config to Perceptor"""

    user = f"""Goal: {goal}

FAILURES:
{failure_report}

MISSING FILES:
{missing_report}

LOGIC ISSUES:
{logic_report}

EXISTING FILES:
{existing_files}

Create remediation tasks."""

    try:
        start = time.time()
        r = client.chat.completions.create(
            model=CLUSTERS["Optimus"]["models"][0],
            messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
            max_tokens=4096,
            temperature=0.3,
            timeout=120,
        )
        elapsed = time.time() - start
        content = r.choices[0].message.content or ""
        logger.info(f"[REMEDIATION] Planner response in {elapsed:.1f}s")

        data = parse_json_response(content, "remediation")
        if data and ("tasks" in data or "items" in data):
            task_list = data.get("tasks") or data.get("items", [])
            fix_tasks = []
            for t in task_list:
                task = Task(
                    task_id=t.get("task_id", f"FIX{len(fix_tasks)+1}"),
                    description=t.get("description", ""),
                    files=normalize_files(t.get("files", [])),
                    cluster=t.get("cluster", "Ratchet"),
                    depends_on=t.get("depends_on", []),
                    priority=t.get("priority", "high"),
                )
                fix_tasks.append(task)
            logger.info(f"[REMEDIATION] Created {len(fix_tasks)} fix tasks")
            return fix_tasks
        else:
            logger.error("[REMEDIATION] Failed to parse remediation plan")
            return []

    except Exception as e:
        logger.error(f"[REMEDIATION] Error: {e}")
        return []


# -- Pipeline ---------------------------------------------------------------

def run_pipeline(goal, output_dir, max_healing_rounds=3):
    """Main pipeline: plan -> execute -> verify -> heal -> repeat until success."""
    project_path = Path(output_dir)
    project_path.mkdir(parents=True, exist_ok=True)

    logger.info(f"\n{'='*60}")
    logger.info(f"SWARM PIPELINE -- Self-Healing Mode")
    logger.info(f"{'='*60}")
    logger.info(f"Goal: {goal}")
    logger.info(f"Output: {project_path}")
    logger.info(f"Log: {log_file}")
    logger.info(f"Max healing rounds: {max_healing_rounds}")

    rate_limiter = RateLimiter(max_per_minute=35, min_interval=2.0)
    all_files = []
    all_tasks = []
    build_ok = False
    tasks = []
    last_build_error = ""
    same_error_count = 0

    for healing_round in range(max_healing_rounds + 1):
        if healing_round == 0:
            logger.info(f"\n{'='*60}")
            logger.info(f"ROUND 1: INITIAL PLANNING")
            logger.info(f"{'='*60}")
            tasks, type_contracts, architecture = plan_tasks(goal, rate_limiter)
            if not tasks:
                logger.error("No tasks planned. Aborting.")
                return []
        else:
            logger.info(f"\n{'='*60}")
            logger.info(f"HEALING ROUND {healing_round}: REMEDIATION")
            logger.info(f"{'='*60}")

            # If tasks were set by build-fix from previous round, use them directly
            if not tasks:
                missing, empty = verify_files(project_path, all_tasks)
                logic_issues = verify_logic(project_path)
                failed_tasks = [t for t in all_tasks if t.status == "failed"]

                if not missing and not empty and not logic_issues and not failed_tasks:
                    logger.info("[HEALING] All checks passed, no healing needed")
                    break

                tasks = plan_remediation(goal, failed_tasks, missing, logic_issues, all_tasks, rate_limiter, project_path)
                if not tasks:
                    logger.warning("[HEALING] No remediation tasks generated")
                    break

            type_contracts = ""
            architecture = ""

        # Build shared context with import paths
        tasks_list = "\n".join([
            f"- {t.task_id} [{t.cluster}] {t.description}" for t in tasks
        ])
        
        # Build import map from task dependencies
        import_map = []
        for t in tasks:
            if t.depends_on:
                for dep_id in t.depends_on:
                    dep_task = next((x for x in tasks if x.task_id == dep_id), None)
                    if dep_task:
                        import_map.append(f"- {t.task_id} imports from {dep_id}: {dep_task.files[0] if dep_task.files else 'unknown'}")
        
        import_map_str = "\n".join(import_map) if import_map else "No cross-task imports"
        
        shared_context = f"""Project: {goal}

Architecture: {architecture}

Tasks:
{tasks_list}

IMPORT MAP (workers must use these exact paths):
{import_map_str}

TYPE CONTRACTS:
{type_contracts}

DESIGN RULES:
- Colors: cohesive palette (blues #3b82f6/#60a5fa/#1e40af)
- Shadows: 0 4px 6px -1px rgba(0,0,0,0.1)
- Transitions: all 0.2s ease
- Typography: font-weight 600-700 headings
- Spacing: 16-24px padding
- Border-radius: 8-12px cards, 6px buttons
- Dark: #0f172a, #1e293b, #334155
- Light: #f8fafc, #f1f5f9, #e2e8f0"""

        (project_path / "SHARED_CONTEXT.md").write_text(shared_context, encoding="utf-8")

        # Write critical boilerplate files first
        critical_written = write_critical_files(project_path)
        if critical_written:
            logger.info(f"[CRITICAL] Created {critical_written} boilerplate files")

        # Execute tasks
        logger.info(f"\n[EXEC] Running {len(tasks)} tasks...")
        write_lock = threading.Lock()
        max_concurrent = 2
        semaphore = threading.Semaphore(max_concurrent)

        def run_task(t):
            with semaphore:
                files = execute_task(t, shared_context, rate_limiter, project_path)
                if files:
                    # Code review gate before writing
                    reviewed_files = review_code(t, files, shared_context, rate_limiter)
                    if reviewed_files:
                        # Output guardrail before writing
                        validated_files = validate_output(t, reviewed_files, rate_limiter)
                        if validated_files:
                            with write_lock:
                                all_files.extend(validated_files)
                                for f in validated_files:
                                    path = f.get("path", "")
                                    content = f.get("content", "")
                                    if path and content:
                                        target = project_path / path
                                        target.parent.mkdir(parents=True, exist_ok=True)
                                        target.write_text(content, encoding="utf-8")
                                        logger.info(f"  -> {path}")
                                # Create skill from successful task
                                create_skill_from_task(t, validated_files, project_path)

        wave = 0
        pending = [t for t in tasks if t.status == "pending"]
        while pending:
            ready = get_ready_tasks(tasks)
            if not ready:
                stuck = [t for t in tasks if t.status == "pending"]
                if stuck:
                    logger.warning(f"[DEPENDENCY] Stuck: {[t.task_id for t in stuck]} -- running anyway")
                    for t in stuck[:max_concurrent]:
                        t.depends_on = []
                else:
                    break

            wave += 1
            logger.info(f"\n[WAVE {wave}] Running {len(ready)} tasks: {[t.task_id for t in ready]}")

            threads = []
            for t in ready:
                t.status = "running"
                thread = threading.Thread(target=run_task, args=(t,))
                threads.append(thread)
                thread.start()

            for thread in threads:
                thread.join(timeout=300)

            pending = [t for t in tasks if t.status == "pending"]

        all_tasks.extend(tasks)
        tasks = []  # Reset so next round doesn't reuse

        # Always try install + build -- compiler errors give better signal than import checks
        install_ok, install_errors = install_deps(project_path)
        if not install_ok:
            logger.error("[INSTALL] Dependencies failed, feeding errors to planner")
            build_fix_tasks = plan_build_fix(goal, install_errors, rate_limiter, project_path)
            if build_fix_tasks:
                tasks = build_fix_tasks
                continue
            logger.error("[INSTALL] Planner could not generate fixes, giving up")
            break

        build_ok, build_errors = build_project(project_path)
        if build_ok:
            logger.info(f"\n{'='*60}")
            logger.info(f"BUILD SUCCEEDED -- PROJECT COMPLETE")
            logger.info(f"{'='*60}")
            break
        else:
            # Circuit breaker: if same error 3 times in a row, stop
            error_key = build_errors[:200]
            if error_key == last_build_error:
                same_error_count += 1
                if same_error_count >= 3:
                    logger.error(f"[BUILD] Same error {same_error_count} times in a row, stopping loop")
                    break
            else:
                same_error_count = 0
            last_build_error = error_key

            logger.error("[BUILD] Build failed, feeding errors to planner")
            build_fix_tasks = plan_build_fix(goal, build_errors, rate_limiter, project_path)
            if build_fix_tasks:
                tasks = build_fix_tasks
                continue
            logger.error("[BUILD] Planner could not generate fixes, giving up")
            break

    # Final summary
    logger.info(f"\n{'='*60}")
    logger.info(f"PIPELINE FINAL SUMMARY")
    logger.info(f"{'='*60}")

    done = [t for t in all_tasks if t.status == "done"]
    failed = [t for t in all_tasks if t.status == "failed"]
    missing, empty = verify_files(project_path, all_tasks)
    logic_issues = verify_logic(project_path)

    logger.info(f"Total tasks: {len(all_tasks)} ({len(done)} done, {len(failed)} failed)")
    logger.info(f"Total files: {len(all_files)} written")
    logger.info(f"Missing files: {len(missing)}")
    logger.info(f"Logic issues: {len(logic_issues)}")
    logger.info(f"Build: {'PASSED' if build_ok else 'FAILED'}")

    for t in all_tasks:
        status = "[OK]" if t.status == "done" else "[FAIL]" if t.status == "failed" else "[WAIT]"
        logger.info(f"  {status} {t.task_id} [{t.cluster}/{t.model_used}] {t.elapsed:.1f}s")

    summary = {
        "goal": goal,
        "timestamp": timestamp,
        "tasks_total": len(all_tasks),
        "tasks_done": len(done),
        "tasks_failed": len(failed),
        "files_written": len(all_files),
        "missing_files": [m["file"] for m in missing],
        "logic_issues": logic_issues,
        "build_passed": build_ok,
        "log_file": str(log_file),
    }
    (project_path / "swarm_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    return all_files


# -- CLI --------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python -m autobots.swarm_pipeline 'Build a tic-tac-toe game' D:\\projects\\output [--rounds N]")
        sys.exit(1)

    goal = sys.argv[1]
    output = sys.argv[2]
    max_rounds = 999
    if "--rounds" in sys.argv:
        idx = sys.argv.index("--rounds")
        if idx + 1 < len(sys.argv):
            max_rounds = int(sys.argv[idx + 1])
    run_pipeline(goal, output, max_healing_rounds=max_rounds)
